### ISSUE TITLE
Make child pages accessible directly from a URL?

### ISSUE THREAD

**Issue by kerimoyle** [libcellml/website-src#1]
Currently pages like this one ( https://libcellml.github.io/apidocs/classlibcellml_1_1Variable ) are not found when accessed through their URL.  They are found only by navigating from the main index page.

**Comment by hsorby** [comment]
I think this is now fixed. Please test and close this issue if this is the case.

**Comment by kerimoyle** [comment]
Yep, all good, thanks :)
