### ISSUE TITLE
move CC icon to the right

### ISSUE THREAD

**Issue by kerimoyle** [libcellml/website-src#111]
I find it really distracting to have the large logo right in the middle of the footer.  It should move to the RHS of the footer bar, be a less contrasting colour, or somehow just not be so annoying ...

**Comment by agarny** [comment]
How do you mean "large"? The size of the CC logo seems very reasonable to me, or am I missing something?

<img width="1867" alt="Screen Shot 2021-03-01 at 09 16 24" src="https://user-images.githubusercontent.com/602265/109432169-d85e9300-7a6e-11eb-96ff-9115c1f6f310.png">

**Comment by kerimoyle** [comment]
Eh, it's a lot larger than the text that was there before.  If it needs to be a logo for some reason, it should be moved out of the reading line towards the right hand side.  Then it's still on every page, it's still a logo, but it doesn't get in the way so much.  This is black, and even our text is not black, so it really stands out!

**Comment by agarny** [comment]
Looking at what we have done for "Acknowledgments", I would probably replace the CC logo with a link that reads "License".

**Comment by nickerso** [comment]
good to keep the logo as it makes it instantly recognisable. Moving it to the left makes sense to me.

**Comment by kerimoyle** [comment]
Closed by #116
