### ISSUE TITLE
Sidebar is always in overlay mode

### ISSUE THREAD

**Issue by hsorby** [libcellml/website-src#130]
The sidebar seems to always be in overlay mode for any width of viewport now.  It should be moved in from the side when the viewport is wide enough to handle it.

![image](https://user-images.githubusercontent.com/778048/109727416-316a2a80-7c19-11eb-8c25-285931a84082.png)

**Comment by kerimoyle** [comment]
Interesting.  This is not what I see!  Did you click the menu hamburger to expand it?  Do you see it at wide screen widths too?  I suspect it's from the buggy icon when we had to make the collapse later ... 

![image](https://user-images.githubusercontent.com/46887220/109729220-6c219200-7c1c-11eb-8930-8d8e1ac63e9c.png)

**Comment by kerimoyle** [comment]
The buggy button is huge!  I'll make it smaller :)

![image](https://user-images.githubusercontent.com/46887220/109729849-64aeb880-7c1d-11eb-8a58-d1eb227d7835.png)

**Comment by hsorby** [comment]
I must have tricked into being in overlay mode when resizing.  I can't get the same effect anymore.

**Comment by kerimoyle** [comment]
OK, but I'm still going to resize the buggy button.  We have a lot of empty space that doesn't need to be there.

**Comment by kerimoyle** [comment]
Closing as resolved already
