### ISSUE TITLE
Doxygen errors on some pages

### ISSUE THREAD

**Issue by kerimoyle** [libcellml/website-src#2]
This page: https://libcellml.github.io/apidocs/classlibcellml_1_1Variable contains "missing" messages:
![Screen Shot 2020-06-04 at 1 13 10 PM](https://user-images.githubusercontent.com/46887220/83704476-4bfd7c00-a666-11ea-8e7b-f6a413184284.png)

**Comment by hsorby** [comment]
I have fixed this now.
