### ISSUE TITLE
Make sure direct links are allowed

### ISSUE THREAD

**Issue by kerimoyle** [libcellml/website-src#23]
At present, all links are being redirected to the home page.  We need to make sure that we can link to internal pages (including bookmarks!) too.

eg: https://staging.libcellml.org/documentation/api/v0.1.0/classlibcellml_1_1Variable takes you to the homepage not the variable class

**Comment by kerimoyle** [comment]
Does this sound familiar at all @hsorby? 

https://stackoverflow.com/questions/62285912/vue-direct-url-is-not-working-only-router-link-click

**Comment by kerimoyle** [comment]
Or this? https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations

**Comment by hsorby** [comment]
It is familiar but not quite what we want I think.  I have seen something that I think would work for us but have currently misplaced it.

**Comment by hsorby** [comment]
I think I shall try this: https://stackoverflow.com/questions/47677220/vuejs-history-mode-with-github-gitlab-pages
I think it is the solution for us.

**Comment by kerimoyle** [comment]
OK, great.  I'll stay away from router stuff for a while then :)

**Comment by hsorby** [comment]
I think the direct links are fixed.  That means they work for me.  If someone else can confirm then we can close this issue.

**Comment by kerimoyle** [comment]
Yes, it works for me too.  The images still don't, but that's a separate thing I guess.  Closing now, thanks!  #59
