### ISSUE TITLE
Force latest version of vue-sphinx-xml

### ISSUE THREAD

**Issue by kerimoyle** [libcellml/website-src#29]
The errors being thrown and preventing some pages from loading come from an older version of `vue-sphinx-xml`.  We should force it to use the most recent version.

![image](https://user-images.githubusercontent.com/46887220/105655961-0e679f00-5f26-11eb-84e8-8ca88a34df07.png)

**Comment by hsorby** [comment]
We need to publish a newer version I think so that the website build can install it.

**Comment by kerimoyle** [comment]
Yep.  I don't know what to change the requirements in the `packages.json` file to be to pick up the newest version?  It's currently `"vue-sphinx-xml": "^0.1.1-alpha.5",`. Or is that what you mean by "publish"? ie: make a version number that can be used?

**Comment by hsorby** [comment]
No we have to `publish` a new version `0.1.1-alpha.6` to [npm js](npmjs.org) before the website build will be able to with it.

**Comment by kerimoyle** [comment]
Ah, ok, ta.  I thought it was through github :) That explains why I couldn't figure it out!

**Comment by hsorby** [comment]
Closing this issue as new versions of `vue-sphinx-xml` have to be produced through npmjs.
