### ISSUE TITLE
Bookmarks with human readable names?

### ISSUE THREAD

**Issue by kerimoyle** [libcellml/website-src#3]
I'm not sure if it's possible, but it would be really nice to be able to link to a function bookmark directly.  At present the bookmark to replaceUnits is: https://libcellml.github.io/apidocs/classlibcellml_1_1Model#classlibcellml_1_1Model_1aa526cbea5a87fe41a4c602fd0c15e40c ?

Something more predictable like: https://libcellml.github.io/apidocs/classlibcellml_1_1Model#replaceUnits would be perfect ... ?

**Comment by hsorby** [comment]
This could be a tough one.  What you see there is the default reference given by Doxygen.

It gets even more complicated when you start having overloaded methods like `replaceUnits`. What would you be expecting there for the overloaded methods?

**Comment by kerimoyle** [comment]
I'd imagine just a link to the first function of that name would be fine.  They should all have a "see also" or "overload" tag within the overload family in any case?

**Comment by kerimoyle** [comment]
Closed by #24
