### ISSUE TITLE
All image paths are broken ...

### ISSUE THREAD

**Issue by kerimoyle** [libcellml/website-src#50]
Images in the XML documents are not showing up.  They are in my local version, as well as in my test site for `vue-sphinx-xml`, but not in staging.  Is there a different base path that's given in staging?

See: https://staging.libcellml.org/documentation/guides/v0.1.0/tutorials/tutorial4/index

**Comment by hsorby** [comment]
The path looks correct in the page and in the staging repository.  I think it might be something to do with the direct links not working.

**Comment by hsorby** [comment]
Given that the direct links are working and images are not maybe the paths to the images are not correct after all.  I am continuing to look into this.

**Comment by kerimoyle** [comment]
Actually, not *all* image paths are broken (since I included the theory in the xml, those ones work), so I suspect it's something on a lower level.  I think I know where it is ...

**Comment by hsorby** [comment]
I think this has now been fixed with #62.  If someone else can confirm that all images are now loaded then we can close this issue.

**Comment by agarny** [comment]
Where are those images? In the developers' documentation (which, incidentally is called "Developer Guidelines" when we click on the link)? I have seen some there, and they all seem to be fine.

**Comment by hsorby** [comment]
I don't know where they all are but there is the one linked above in the users' guides and the developers' has images here: https://staging.libcellml.org/documentation/developers/v0.2.0/dev_setup#setting-up-the-codebase

**Comment by agarny** [comment]
Yes, I went through that page among others. Just checked the various tutorials and they seem fine too (only tutorial 4 has an image?).

**Comment by hsorby** [comment]
Closing this issue as images are now loaded as expected.
