### ISSUE TITLE
Why is the breadcrumb right aligned?

### ISSUE THREAD

**Issue by agarny** [libcellml/website-src#64]
Any particular reason why the breadcrumb is right aligned? I would expect it to be left aligned, so that the "house" is always in the same place while right now it keeps moving around, which looks odd to me.

**Comment by kerimoyle** [comment]
Reason 1) I thought it looked nice ;)
Reason 2) Internally, the breadcrumbs are right-to-left text blocks, so that when there's overflow it collapses from the left (ie: least important links) first.

I can change it to be a combo deal if it's that important ...

**Comment by agarny** [comment]
I would have it left-aligned. This is what you can see in 99% of (all?) websites. Just look at GitHub for instance.

**Comment by kerimoyle** [comment]
Closed by #72
