### ISSUE TITLE
Use KaTeX instead of MathJax?

### ISSUE THREAD

**Issue by agarny** [libcellml/website-src#68]
Any particular reason why we use MathJax rather than KaTeX? In fact, which version of MathJax are we using? Either way, whether we use MathJax 2.7 or 3, KaTeX is (significantly in the case of MathJax 2.7) faster (see https://www.intmath.com/cg5/katex-mathjax-comparison.php). Also, it's very easy to deploy and update.

**Comment by hsorby** [comment]
No particular reason.  If memory serves then it was due to what Sphinx uses to generate Math from LaTex.

**Comment by kerimoyle** [comment]
It comes from the `vue-mathjax` dependency which is inside `vue-sphinx`.  It used to render anything in the text that was in brackets as maths: `I am (not maths!)` -> I am *notmaths!* 
This only was fixed when I explicitly included `vue-mathjax` in the project ... but now there are other hiccups that need investigation too :|

**Comment by agarny** [comment]
FWIW, it's very simple to get Sphinx to generate Math using KaTeX (I do it for the OpenCOR documentation and it took me less than 10 minutes to set it up). As for Vue, I can see that there is [vue-katex](https://www.npmjs.com/package/vue-katex). Would it be worth looking, in case it would address those other hiccups you mention @kerimoyle?

**Comment by kerimoyle** [comment]
I'm going to look first at the rst files to make sure there are no mistakes there.  I'll look into that afterwards, thanks :)

**Comment by kerimoyle** [comment]
Closed by #135
