### ISSUE TITLE
Capture contributions to various aspects of libCellML

### ISSUE THREAD

**Issue by nickerso** [libcellml/website-src#93]
Currently we simply link to https://github.com/cellml/libcellml/graphs/contributors for "all contributors to libCellML". But now with the separation of website, documentation, tutorials, etc, we need to reach more broadly to ensure all contributors are mentioned. Not sure if we'd want to classify contributions, but that could also be something to explore.

Short term suggested fix: link to contributor pages for all relevant repos.

Longer term suggest fix: part of building the website could use the github api to pull out listing of contributors across all relevant repositories.

**Comment by kerimoyle** [comment]
I've scraped some contributions from github ... though it feels a bit like double-dipping to list them all!
Are there any other repos/sources we need to look at?
![image](https://user-images.githubusercontent.com/46887220/108644668-d9df0700-7514-11eb-9d81-441b7b127c37.png)

**Comment by hsorby** [comment]
I think this is now addressed.
![image](https://user-images.githubusercontent.com/778048/109275862-2b232980-787a-11eb-9fe2-54d8631a95e6.png)

**Comment by kerimoyle** [comment]
Closed by lots of PRs ...
